version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Tranhuutri@123 # Password phải khớp với application.properties
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always # Tự động chạy lại nếu database chưa sẵn sàng

volumes:
  sqlserver_data: # Lưu trữ dữ liệu DB không bị mất khi tắt Docker